package com.alex.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.alex.bean.CommodityBean;

import com.alex.dao.CommodityBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commodityBeanDaoConfig;

    private final CommodityBeanDao commodityBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commodityBeanDaoConfig = daoConfigMap.get(CommodityBeanDao.class).clone();
        commodityBeanDaoConfig.initIdentityScope(type);

        commodityBeanDao = new CommodityBeanDao(commodityBeanDaoConfig, this);

        registerDao(CommodityBean.class, commodityBeanDao);
    }
    
    public void clear() {
        commodityBeanDaoConfig.getIdentityScope().clear();
    }

    public CommodityBeanDao getCommodityBeanDao() {
        return commodityBeanDao;
    }

}
